
title: Nat's Coding Adventure
email: nfunk@sfu.ca
description: >- # this means to ignore newlines until "baseurl:"
  This site is dedicated to making small steps toward becoming a better programmer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: NFunkAtSFU
github_username:  NFunkAtSFU

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes 
